name: native-metrics build  

on:
  push:
  workflow_dispatch:

jobs:
  linux-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm ci
    - name: Run build
      run: npm run build
  
  win-build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Get Node Version
      id: node_version
      run: echo "::set-output name=version::$(node --version | sed 's/^.//')"

    # https://github.com/nodejs/node-gyp/blob/master/docs/Updating-npm-bundled-node-gyp.md#windows
    - name: Upgrade node-gyp in npm
      run: |
        cd "C:\hostedtoolcache\windows\node\${{ steps.node_version.outputs.version }}\x64"
        cd node_modules\npm\node_modules\@npmcli\run-script
        npm install node-gyp@>=8.4.0

    - name: Install Dependencies
      run: npm ci
    - name: Run build
      run: npm run build
  
  mac-build:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm ci
    - name: Run build
      run: npm run build
