name: native-metrics CI

on:
  pull_request:
  push:
    branches:
      - '**'
    tags-ignore: # Do not run for tags
      - '**'
  workflow_dispatch:


jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [lts/*]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm ci
    - name: Run Linting
      run: npm run lint

  linux:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm ci
    - name: Rebuild
      run: npm run rebuild
    - name: Run Unit
      run: npm run unit
    - name: Run Integration
      run: npm run integration

  windows-2019:
    runs-on: windows-2019

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm ci
    - name: Rebuild
      run: npm run rebuild
    - name: Run Unit
      run: npm run unit
    - name: Run Integration
      run: npm run integration

  windows-latest:
    runs-on: windows-latest

    # Node 16+ should eventually bundle node-gyp>=8.4.0 to be compatible with Server 2022.
    # Once compatible, can remove node-gyp upgrade.
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Get Node Version
      id: node_version
      run: echo "::set-output name=version::$(node --version | sed 's/^.//')"

    # https://github.com/nodejs/node-gyp/blob/master/docs/Updating-npm-bundled-node-gyp.md#windows
    - name: Upgrade node-gyp in npm
      run: |
        cd "C:\hostedtoolcache\windows\node\${{ steps.node_version.outputs.version }}\x64"
        cd node_modules\npm\node_modules\@npmcli\run-script
        npm install node-gyp@>=8.4.0
    - name: Install Dependencies
      run: npm ci
    - name: Rebuild
      run: npm run rebuild
    - name: Run Unit
      run: npm run unit
    - name: Run Integration
      run: npm run integration
