name: native-metrics CI

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, e.g. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm ci
    - name: Run build
      run: npm run build
    - name: Upload to S3
      run: npm run upload
